In [234]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd

In [235]:

def linear_regresion(x, w0=0, w1=0):
    return w0 + w1 * x


In [236]:
data1 = np.array([2, 3, 4, 5])

data_out = data1 * 3 + 2

resi = linear_regresion(data1)
resi

array([0, 0, 0, 0])

In [237]:
def mse(predicted_results, true_results, w0=0, w1=0):
    sum_of_el = np.sum((linear_regresion(predicted_results, w0, w1) - true_results) ** 2)
    return 1/(2 * len(predicted_results)) * sum_of_el

In [238]:
mse(data1, data_out)

83.75

In [239]:
def grad_decent(x, y, iter=1000, lr=0.01, stopping_value=0.00001):
    we0 = 0
    we1 = 0
    n = len(x)
    prevt_cost = None
    
    for i in range(iter):
        result =linear_regresion(x, we0 , we1)
        costsr = mse(result,y,we0,we1)
        
        if prevt_cost and abs(costsr - prevt_cost) <= stopping_value:
            break
        
        prevt_cost = costsr
        
        intercept = -(1 / n) * np.sum(x * (y - result))
        slope = -(1 / n) * np.sum(y - result)
    
        we0 -= slope * lr
        we1 -= intercept * lr

    return we0,we1
        

In [240]:
w0,w1 = grad_decent(data1,data_out)

In [241]:
print(linear_regresion(data1, w0, w1).round())
print(data_out.round())

[ 8. 11. 14. 17.]
[ 8 11 14 17]


In [258]:
df1 = pd.read_csv("Housing.csv")
df = pd.DataFrame(df1)

X = df[['area', 'bedrooms', 'bathrooms']].values
y = df['price'].values


def mult_lin_reg(dataf, weight):
    return weight[0] + np.dot(dataf, weight[1:])

def mse(pr_result, right_res):
    return 1 / (2 * len(pr_result)) * np.sum((pr_result - right_res) ** 2)

def grad_descent(x, y, iter=1000, lr=0.01, stopping_value=0.00001):
    weights = np.zeros(X.shape[1] + 1)
    prev_cost = np.inf
    
    for _ in range(iter):
        pr_result = mult_lin_reg(x, weights)
        cost = mse(pr_result, y)
        
        if np.abs(prev_cost - cost) <= stopping_value:
            break
        
        prev_cost = cost
        gradients = np.dot(x.T, (pr_result - y)) / len(y)
        gradients = X.shape[1] 
        
        weights[1:] -= lr * gradients
        weights[0] -= lr * np.mean(pr_result - y)
        
    return weights

weights = grad_descent(X, y)

print("Optimal weights:", weights)




Optimal weights: [ 4.90570353e+06 -3.00000000e+01 -3.00000000e+01 -3.00000000e+01]


In [248]:

predictions = mult_lin_reg(X, weights)

print("Predicted prices:", predictions)

Predicted prices: [4682923.53151008 4636663.53151008 4606753.53151008 4680523.53151008
 4682953.53151008 4680523.53151008 4648093.53151008 4419463.53151007
 4662553.53151008 4733053.53151008 4509583.53151008 4725493.53151008
 4709023.53151008 4800523.53151008 4671553.53151008 4725553.53151008
 4707523.53151008 4650553.53151008 4767553.53151008 4712953.53151008
 4775983.53151008 4690903.53151008 4664083.53151008 4768753.53151008
 4641553.53151008 4709323.53151008 4725553.53151008 4639333.53151008
 4666993.53151008 4740523.53151008 4681303.53151008 4695583.53151008
 4759123.53151008 4726723.53151008 4700323.53151008 4695553.53151008
 4681093.53151008 4635523.53151008 4725583.53151008 4725523.53151008
 4709083.53151008 4714753.53151008 4711153.53151008 4725523.53151008
 4725523.53151008 4725553.53151008 4725553.53151008 4707583.53151008
 4776553.53151008 4682353.53151008 4682353.53151008 4715833.53151008
 4725523.53151008 4751053.53151008 4725553.53151008 4725583.53151008
 4562353.5315100

In [254]:

X = df[['area','bedrooms','bathrooms']].values
y = df['price'].values

X_with_ones = np.hstack((np.ones((X.shape[0], 1)), X))

coeffs = np.linalg.inv(X_with_ones.T @ X_with_ones) @ X_with_ones.T @ y

print("Аналітичні коефіцієнти:", coeffs)




Аналітичні коефіцієнти: [-1.73171608e+05  3.78762754e+02  4.06820034e+05  1.38604950e+06]


In [252]:
lr_model = LinearRegression().fit(X, y)

print("Коефіцієнти з LinearRegression:", lr_model.coef_, lr_model.intercept_)

Коефіцієнти з LinearRegression: [3.78762754e+02 4.06820034e+05 1.38604950e+06] -173171.60763263702


In [256]:
y_pred_analytical = X_with_ones @ coeffs
y_pred_lr = lr_model.predict(X)

print("Порівняння результатів:")
print("Аналітичне рішення:", y_pred_analytical)

Порівняння результатів:
Аналітичне рішення: [ 7036627.15462756 10392020.79073062  7591864.51496455  7066928.17491437
  5650577.65683656  8046157.63893619  8862041.44657728 12155033.66266496
  5908136.32927444  5997273.32237126  7433006.33878929  7884833.54232771
  6707103.55900852  5551877.16057395  6773736.96722072  5112734.54674572
  6726041.69668778  7038870.89473029  5561696.15574839  6251044.36727328
  4069593.08695356  6529434.99115833  5482378.157826    5546545.64560498
  7152499.72080582  6703315.93147267  6091964.01076753  5794857.42953371
  7644191.44779685  6309402.66774416  6650639.07230556  5084677.26656164
  6074569.7605214   7462862.99841513  5837715.29352639  6470726.76435264
  6653290.41158066  7635072.30529203  4705914.51297653  6498784.04453672
  4914234.02744834  6228318.60205817  6273770.13248838  6498784.04453672
  6498784.04453672  6091964.01076753  6091964.01076753  4933172.1651276
  5448067.32967285  6637382.37593008  6637382.37593008  4829012.40789169
  649878

In [257]:
print("LinearRegression:", y_pred_lr)

LinearRegression: [ 7036627.15462756 10392020.79073062  7591864.51496455  7066928.17491437
  5650577.65683656  8046157.63893619  8862041.44657728 12155033.66266496
  5908136.32927443  5997273.32237125  7433006.33878929  7884833.54232771
  6707103.55900852  5551877.16057395  6773736.96722072  5112734.54674571
  6726041.69668777  7038870.89473029  5561696.15574838  6251044.36727327
  4069593.08695356  6529434.99115833  5482378.157826    5546545.64560498
  7152499.72080582  6703315.93147267  6091964.01076753  5794857.42953371
  7644191.44779685  6309402.66774416  6650639.07230556  5084677.26656164
  6074569.7605214   7462862.99841512  5837715.29352638  6470726.76435263
  6653290.41158066  7635072.30529203  4705914.51297653  6498784.04453671
  4914234.02744834  6228318.60205817  6273770.13248838  6498784.04453671
  6498784.04453671  6091964.01076753  6091964.01076753  4933172.16512759
  5448067.32967285  6637382.37593008  6637382.37593008  4829012.40789169
  6498784.04453671  5770015.67022